### PR TITLE
Compatibilityv0.5

### PR DESCRIPTION
**Pull request by awbsmith**

### CODE REVIEW

**Comment by c42f** [comment]
:ship: :it:

**Comment by awbsmith** [comment]
[:ship: :it:?](
https://upload.wikimedia.org/wikipedia/commons/c/c7/Collision_of_Costa_Concordia_11.jpg)

**Comment by c42f** [comment]
@awbsmith not quite what I had in mind!

**Comment by awbsmith** [comment]
Merged at commit:
287190b378538789c5e1f70ef9e533fc6626d010

**Pull request closed without merging**
