### PR TITLE
add pow methods for known easy cases

### PR DESCRIPTION
**Pull request by simonbyrne**
This should make it more convenient to work with angular velocities. Not sure how best to handle the other types: let me know if you have suggestions.

### CODE REVIEW

**Comment by c42f** [comment]
Thanks Simon, it's nice to have these.

The `Quat` case should also be fairly straightforward, I guess - I think it's very related to spherical linear interpolation with the identity as the initial rotation (https://en.wikipedia.org/wiki/Slerp)?  Also applies to `SPQuat`, via the `SPQuat <-> Quat` mapping, I'm not sure if there's a better way for that.

It would also be nice to add versions for `RotX, RotY, RotZ`.

As to the combined Euler or Tait-Bryant types like RotXY, I don't have much hope for a nice version of those!  Perhaps the best we can do there is to convert to a `Quat` or one of the other parameterizations, and then perform the power?  Same for `RotMatrix`, I assume.

For the cases where there's no good algorithm we currently know about, I'd be happy with a generic fallback, perhaps something roughly like:

```julia
@inline Base.:^(r::Rotation{3}, t::Real) = convert(Quat, r)^t
```

with `Quat` replaced by whatever type is generally more efficient.

**Comment by c42f** [comment]
Hmm, it looks like quaternion power may defined reasonably efficiently in terms of `exp(::Quat)` and `log(Quat)` which are fairly simple to implement. http://math.stackexchange.com/questions/939229/unit-quaternion-to-a-scalar-power has a bit of a discussion and this is how it's done in Quaternions.jl.

**Comment by simonbyrne** [comment]
Looks like `AngleAxis` is the simplest one (quaternion powers seem to be equivalent to converting to angle-axis and back again).

Where is the best place for tests?

**Comment by andyferris** [comment]
Thanks Simon, I like this, but I think it would be great to have a fallback for general rotations. Going through `AngleAxis` seems most straightforward to me (if there is a more efficient way, that could easily be implemented in a different PR).

> Where is the best place for tests?

I'm not fussy, but `rotation_tests.jl` seems OK?

**Comment by andyferris** [comment]
I'm also trying to remember if there were assumptions anywhere about `AngleAxis` angles or Rodriguez vector norms being small? Probably not, but its been a while since I have been over the code.

There is a small problem here in that `(rot^a)^b` would be different here if `AngleAxis` automatically truncated to (-pi, pi], say, or not. What behaviour would people want? Generally these objects represent a pi rotation and a 3pi rotation as the same thing, for instance...

**Comment by andyferris** [comment]
> Generally these objects represent a pi rotation and a 3pi rotation as the same thing, for instance...

To expand, I would assert that converting rotations between different formats should have no observable consequences (beyond machine precision issues), so `AngleAxis(3pi, 1.0, 0, 0) ^ 0.5` and `RotMatrix(AngleAxis(3pi, 1.0, 0, 0)) ^ 0.5` should behave the same (the latter behaving like `AngleAxis(pi, 1.0, 0, 0) ^ 0.5`).

**Comment by c42f** [comment]
Converting between rotation parameterizations shouldn't have observable consequences relative to their role as linear operators, so yes it seems sensible to return `AngleAxis` from `^` as a general fallback.  (Side note - which parameterization is in use obviously has an effect if you're trying to extract the parameters... I think the API currently falls down a bit there, eg for RotXYZ what I end up doing is referring to the fields explicitly... not sure if that's the right thing.)

> Should the inner constructor of AngleAxis make sure that theta falls in a certain range?

I'd say no.  What's the purpose of limiting this? Is it a contract with users that the angle is always wrapped within a given range?  I'd guess that most use cases don't need this, but if we do it as a matter of course it'll be extra compute in every case.  Maybe better would be a function which extracts parameters from a given `Rotation` and puts them in some canonical form, instead of explicitly referring to the fields?

**Comment by andyferris** [comment]
Sorry - I'm slightly confused what you think we should do here.

Given `n` integer, then `AngleAxis(theta + 2*n*pi, a, b, c) ^ x` needs to behave *exactly* like `AngleAxis(theta, a, b, c) ^ x` - because both are equal as a `RotMatrix` (and all rotations inherit from `AbstractArray` and the answer to `^` has to agree with the `Base` definition). 

AFAIK all the operations prior to this PR have this property, but AFAICT as it stands this PR does not respect this rule.

**Comment by simonbyrne** [comment]
My application is that I want to be represent rotational velocity from a gyroscopic sensor, which returns yaw, pitch, roll readings (i.e. `RodriguesVec` velocity) to update my orientation state. Though unlikely in my particular application, it is quite possible to have more than one rotation per time unit.

I would argue that this is a case where the deviation from `AbstractArray` behaviour is okay: there is a certain amount of ambiguity to the definition of fractional matrix powers (integer powers are unaffected), similar to branch cuts for complex-valued functions. Moreover, it is a fairly esoteric operation, as evinced by the fact that `[0.0 -1.0; 1.0 0.0]^0.2` has been broken in Base for a long time (at least since 0.4).

**Comment by simonbyrne** [comment]
In fact, complex number provide a certain amount of precedence here for values which are "equal" but give different powers:
```
julia> z = Complex(-1.0,0.0)
-1.0 + 0.0im

julia> z == conj(z)
true

julia> z^0.5 == conj(z)^0.5
false
```

**Comment by c42f** [comment]
The confusion here seems to be that an angular velocity isn't a `Rotation`, if you think subtypes of `Rotation` should behave only as elements of the group SO(3).  However, the set of angular velocities and the group SO(3) is isomorphic if you restrict yourself to low rotation rates.

So here's the interesting bit:

* The types `RodriguesVec` and `AngleAxis` form a multiple cover of SO(3), in such a way that they're fine for representing angular velocities.  Arguably, `RodriguesVec` is *the* natural representation of an angular velocity.
* The parameterizations `Quat`, `SPQuat` form a double cover of SO(3).  No good for angular velocities.
* The set of all `RotMatrix` with constraints, being SO(3) is no good for angular velocities.

So, what kind of thing do we think `Rotation` is?

To me, it's quite useful and meaningful to allow `RodriguesVec` and `AngleAxis` to represent arbitrary angular velocities, though it conflates different mathematical objects.  What's the best way to deal with this?  Clear documentation about this source of confusion might do?

**Comment by c42f** [comment]
By the way Simon, when I've dealt with (admittedly rather specialized and expensive) gyros they've tended to give a Δω as carefully integrated over a given measurement time, as this is what you need for inertial navigation.  This is an actual Rotation, rather than an angular velocity.  Just out of curiosity, what type of gyro are you dealing with?

**Comment by simonbyrne** [comment]
I guess the alternative would be to define a similar set of skew-symmetric matrices which span the tangent space of SO(3). If you wanted to map between these and SO(3) you could overload `log` and `exp`.

Actually, that might be a much more coherent solution.

I'm working at the other end of the spectrum: it's for [SenseHat.jl](https://github.com/JuliaBerry/SenseHat.jl), which has an [one of these chips](http://www.st.com/resource/en/datasheet/lsm9ds1.pdf).

**Comment by c42f** [comment]
Nice, there's a lot of fun to be had at both ends of the inertial navigation spectrum.

> `AngleAxis(theta + 2*n*pi, a, b, c) ^ x` needs to behave exactly like `AngleAxis(theta, a, b, c) ^ x` - because both are equal as a RotMatrix

@andyferris I admit this could be a problem :-)

The suggestion for the skew symmetric matrices would be a mathematically neat solution.  I assume we'd want an abstract type for that, perhaps simply `AngularVelocity` to keep with the geometric theme?  (Arguably clearer than `SkewSymmetric` or `AntiSymmetric`, especially as `Base.Symmetric` is a view.)

**Comment by andyferris** [comment]
I agree with all of the above, which I was coming back here to write anyway :)

I strongly feel that a separate type for the generators/velocities would be ideal, letting them turn into rotations via `exp` and so-on.

However, I think Simon's argument about complex arithmetic has *some* merit, and in the interest of being productive in the short term, we could just merge this?

**Comment by andyferris** [comment]
I'll make an issue for future improvements

**Pull request merged**
