### PR TITLE
Add upper bound on StaticArrays version.

### PR DESCRIPTION
**Pull request by tkoolen**
In anticipation of the next release.

### CODE REVIEW

**Comment by c42f** [comment]
Hmm, on a closer look we're really close to getting away without this (at least if the static arrays changes are confined to https://github.com/JuliaArrays/StaticArrays.jl/pull/134), but not quite, because the abstract `StaticMatrix` would include size parameters and `Rotation` inherits from it.

I think the range `0.4.0 0.5-` might be more appropriate?  @andyferris I assume if you merge the breaking changes in https://github.com/JuliaArrays/StaticArrays.jl/pull/134/files it will be StaticArrays-0.5.0?

**Comment by andyferris** [comment]
Or maybe 0.4+ 0.5- if this is a temporary development release?

**Comment by tkoolen** [comment]
Just wait a couple more days for the next StaticArrays release?

**Comment by c42f** [comment]
@andyferris I'm a bit confused, I don't think `v"0.4+"` is very meaningful in the REQUIRE file - in semver the `+` is meant to separate the version from the build number.  I don't think there's an intentional way to specify an open interval for the lower bound, if that's what you were going for.

@tkoolen Might be more than a few days before the next `StaticArrays` release.

**Comment by tkoolen** [comment]
Alright, changed upper bound to 0.5-.

**Pull request merged**
